# Generated by Django 5.0.1 on 2025-04-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('hardware_version', models.CharField(max_length=50)),
                ('software_version', models.CharField(max_length=50)),
                ('firmware_version', models.CharField(max_length=100)),
                ('vpn_reachable', models.BooleanField(default=True, help_text='Reachable via VPN tunnel')),
                ('telnet_port', models.IntegerField(default=23)),
                ('telnet_username', models.CharField(max_length=100)),
                ('telnet_password', models.CharField(max_length=100)),
                ('snmp_ro_community', models.CharField(help_text='SNMP read-only community', max_length=100)),
                ('snmp_rw_community', models.CharField(help_text='SNMP read-write community', max_length=100)),
                ('snmp_port', models.IntegerField(default=161, help_text='SNMP UDP port')),
                ('iptv_module', models.BooleanField(default=False)),
                ('supported_pon_types', models.CharField(default='GPON', max_length=100)),
                ('tr069_profile', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='inactive', max_length=20)),
                ('uptime', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('env_temperature', models.FloatField(blank=True, null=True)),
                ('power_supply_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('management_vlan', models.IntegerField()),
                ('snmp_version', models.CharField(choices=[('v1', 'Version 1'), ('v2c', 'Version 2c'), ('v3', 'Version 3')], default='v2c', max_length=10)),
                ('snmp_community', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTS',
            },
        ),
        migrations.CreateModel(
            name='ONUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pon_type', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('download_speed', models.CharField(max_length=50)),
                ('upload_speed', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('card_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='network.olt')),
            ],
        ),
        migrations.CreateModel(
            name='PONPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('is_outage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pon_ports', to='network.olt')),
            ],
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('signal_strength', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='network.onutype')),
                ('pon_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='network.ponport')),
            ],
        ),
        migrations.CreateModel(
            name='UplinkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplink_ports', to='network.olt')),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='network.olt')),
            ],
        ),
        migrations.CreateModel(
            name='ODB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbs', to='network.zone')),
            ],
        ),
    ]
