# Generated by Django 5.0.1 on 2025-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='last_metrics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
