# Generated by Django 5.0.1 on 2025-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_olt_last_metrics_update_olt_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='memory_free',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='memory_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='metrics_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='metrics_status',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='olt',
            name='storage_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
