# Generated by Django 5.0.1 on 2025-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_olt_memory_free_olt_memory_total_olt_metrics_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='port_count',
            field=models.IntegerField(default=0, help_text='Number of ports on this card'),
        ),
    ]
