# Generated by Django 5.0.1 on 2025-05-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_card_port_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponport',
            name='is_outage',
        ),
        migrations.RemoveField(
            model_name='ponport',
            name='olt',
        ),
        migrations.RemoveField(
            model_name='ponport',
            name='port_number',
        ),
        migrations.RemoveField(
            model_name='ponport',
            name='signal_strength',
        ),
        migrations.AddField(
            model_name='ponport',
            name='card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pon_ports', to='network.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponport',
            name='configured_onts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponport',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ponport',
            name='last_snmp_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful SNMP data fetch for this port', null=True),
        ),
        migrations.AddField(
            model_name='ponport',
            name='online_onts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponport',
            name='port_index_on_card',
            field=models.IntegerField(default=0, help_text='Index of the port on the card, e.g., 0-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponport',
            name='rx_power',
            field=models.FloatField(blank=True, help_text='OLT Port Receive Power (dBm)', null=True),
        ),
        migrations.AddField(
            model_name='ponport',
            name='tx_power',
            field=models.FloatField(blank=True, help_text='OLT Port Transmit Power (dBm)', null=True),
        ),
        migrations.AlterField(
            model_name='ponport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
