# Generated by Django 5.0.1 on 2025-05-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_ponport_is_outage_remove_ponport_olt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('olt', 'slot_number')},
        ),
    ]
